# Generated by Django 5.1.11 on 2025-07-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="domainchange",
            name="firebase_error",
            field=models.TextField(
                blank=True, help_text="Firebase update error if any"
            ),
        ),
        migrations.AddField(
            model_name="domainchange",
            name="firebase_etag",
            field=models.CharField(
                blank=True, help_text="Firebase etag after update", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="domainchange",
            name="firebase_updated",
            field=models.BooleanField(
                default=False, help_text="Whether Firebase Remote Config was updated"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="firebase_etag",
            field=models.CharField(
                blank=True, help_text="Last Firebase etag", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="firebase_project_id",
            field=models.CharField(
                blank=True, help_text="Firebase project ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="last_firebase_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersession",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="usersession",
            name="last_activity",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="usersession",
            name="session_key",
            field=models.CharField(
                blank=True, help_text="Django session key", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="app_name",
            field=models.CharField(
                help_text="Application name (appname)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="service_account_data",
            field=models.JSONField(
                default=dict,
                help_text="Firebase service account configuration in JSON format",
            ),
        ),
    ]
