# Generated by Django 5.1.11 on 2025-07-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_domainchange_firebase_error_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersession",
            name="city",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="country",
        ),
        migrations.AddField(
            model_name="domainchange",
            name="firebase_new_value",
            field=models.URLField(blank=True, help_text="New value in Firebase"),
        ),
        migrations.AddField(
            model_name="domainchange",
            name="firebase_old_value",
            field=models.URLField(blank=True, help_text="Previous value from Firebase"),
        ),
        migrations.AddField(
            model_name="project",
            name="firebase_current_url",
            field=models.URLField(
                blank=True,
                help_text="Current URL from Firebase Remote Config 'activity' parameter (source of truth)",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="app_name",
            field=models.CharField(help_text="Application name", max_length=100),
        ),
        migrations.AlterField(
            model_name="project",
            name="firebase_project_id",
            field=models.CharField(
                blank=True,
                help_text="Firebase project ID from service account JSON (e.g., 'royaltv-1b482')",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="service_account_data",
            field=models.JSONField(
                default=dict, help_text="Service account configuration in JSON format"
            ),
        ),
    ]
