# Generated by Django 5.1.11 on 2025-07-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_active_session",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_login_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_user_agent",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="login_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_level",
            field=models.IntegerField(
                choices=[(1, "Administrator"), (2, "Regular User"), (3, "Viewer")],
                default=2,
            ),
        ),
    ]
